name: Deploy to Firebase Hosting

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        run: |
          git clone https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git .
          git checkout ${{ github.sha }}

      - name: Install Dependencies
        run: npm install

      - name: Build Project
        run: npm run build

      - name: Deploy to Firebase Hosting
        run: |
          echo '${{ secrets.FIREBASE_SERVICE_ACCOUNT }}' > service-account.json
          ls -la service-account.json
          export GOOGLE_APPLICATION_CREDENTIALS=service-account.json
          ./node_modules/.bin/firebase deploy --only hosting --non-interactive --project gen-lang-client-0640114821 --debug
