name: Deploy to Firebase Hosting

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Dependencies
        run: npm install

      - name: Build Project
        run: npm run build
        env:
          VITE_SUPABASE_URL: 'https://otofpzsdyfxmqvigklnb.supabase.co'
          VITE_SUPABASE_ANON_KEY: 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im90b2ZwenNkeWZ4bXF2aWdrbG5iIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Nzc5NzA2MTEsImV4cCI6MjA5MzU0NjYxMX0.8Ym6wBMYNLwH_Fj-I6CJBrH70X06eRMzU_p9uWhjoVk'

      - name: Deploy to Firebase Hosting
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT }}'
          channelId: live
          projectId: gen-lang-client-0640114821
